name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Omogućava puni git history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Stavi verziju koja ti odgovara
          cache: npm

      - name: Install dependencies
        run: npm ci  # Brže i sigurnije od `npm install`

      - name: Build project with Vite
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: dist

      - name: Verify downloaded files
        run: ls -la dist  # Proveri da li je build ispravno preuzet

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
